### ISSUE TITLE
Internal Server Error on `search_for_lists()`

### ISSUE THREAD

**Issue by CalebMDMI** [ansys/grantami-recordlists#300]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

#### Description
Error when performing a search for record lists.

#### Log
```
2024-07-30 09:28:37,274  - INFO     - _connection.search_for_lists.137 - Searching for lists with connection <RecordListsApiClient url: https://[ REDACTED ]/mi_servicelayer>
2024-07-30 09:28:37,275  - DEBUG    - _models._to_model.530 - Serializing SearchCriterion to API model
2024-07-30 09:28:37,276  - DEBUG    - _models._to_model.549 - {'contains_records': None,
 'contains_records_in_databases': None,
 'contains_records_in_integration_schemas': None,
 'contains_records_in_tables': ['c5887785-9f5d-4b4d-a096-[ REDACTED ]'],
 'is_awaiting_approval': None,
 'is_internal_use': None,
 'is_published': True,
 'is_revision': None,
 'name_contains': None,
 'type': 'recordList',
 'user_can_add_or_remove_items': None,
 'user_role': None}
2024-07-30 09:30:17,425  - ERROR    - main.main.46 - ApiException(500, 'Internal Server Error')
HTTP response headers: {'Cache-Control': 'private', 'Content-Type': 'application/octet-stream', 'Server': 'Microsoft-IIS/10.0', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000', 'Date': 'Tue, 30 Jul 2024 16:30:10 GMT', 'Content-Length': '20'}
HTTP response body: A task was canceled.
Traceback (most recent call last):
  File "main.py", line 35, in main
  File "main.py", line 159, in validity_email_section
  File "validity\reporting\reporter.py", line 29, in report
  File "validity\reporting\reporter.py", line 59, in create_records_worksheet
  File "validity\reporting\record_lists.py", line 30, in get_record_list_membership
  File "ansys\grantami\recordlists\_connection.py", line 141, in search_for_lists
  File "ansys\grantami\serverapi_openapi\api\list_management_api.py", line 1086, in api_v1_lists_search_post
  File "ansys\grantami\serverapi_openapi\api\list_management_api.py", line 1147, in _api_v1_lists_search_post_with_http_info
  File "ansys\openapi\common\_api_client.py", line 456, in call_api
  File "ansys\openapi\common\_api_client.py", line 177, in __call_api
  File "ansys\openapi\common\_api_client.py", line 544, in request
  File "ansys\openapi\common\_util.py", line 360, in handle_response
ansys.openapi.common._exceptions.ApiException: ApiException(500, 'Internal Server Error')
HTTP response headers: {'Cache-Control': 'private', 'Content-Type': 'application/octet-stream', 'Server': 'Microsoft-IIS/10.0', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000', 'Date': 'Tue, 30 Jul 2024 16:30:10 GMT', 'Content-Length': '20'}
HTTP response body: A task was canceled.
```

#### Code
```python
search_results = utils.PyGranta_API_client.search_for_lists(
        SearchCriterion(contains_records_in_tables=[table.guid], is_published=True),
)
```

#### Background
This error only seems to appear when searching on a specific table; all others work just fine. Are there any properties a table could have that might cause this issue?

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Granta MI 2023R2

### 🐍 Which Python version are you using?

3.11.9

### 📦 Installed packages

```shell
aiosmtpd==1.4.6
altgraph==0.17.4
ansys-grantami-recordlists==1.1.0
ansys-grantami-serverapi-openapi==2.0.0
ansys-openapi-common==1.5.1
atpublic==4.1.0
attrs==23.2.0
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
cryptography==42.0.8
crystalpyze==0.1.6
et-xmlfile==1.1.0
filetype==1.2.0
genson==1.3.0
GRANTA_MIScriptingToolkit==3.3.202
idna==3.7
importlib_metadata==8.0.0
jaraco.classes==3.4.0
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
keyring==23.13.1
MakeDeployRequirements==3.0.1
MarkupSafe==2.1.5
more-itertools==10.3.0
openpyxl==3.1.5
packaging==24.1
pefile==2023.2.7
pip-system-certs==4.0
pycparser==2.22
pycryptodomex==3.20.0
pyinstaller==6.9.0
pyinstaller-hooks-contrib==2024.7
pyparsing==3.1.2
pypiwin32==223
pyspnego==0.11.0
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
pywin32-ctypes==0.2.2
referencing==0.35.1
requests==2.32.3
requests-negotiate-sspi==0.5.2
requests_ntlm==1.3.0
rpds-py==0.19.0
six==1.16.0
sspilib==0.1.0
types-openpyxl==3.1.5.20240630
urllib3==2.2.2
wrapt==1.16.0
yattag==1.15.2
zipp==3.19.2
```

**Comment by CalebMDMI** [comment]
(Edited list of installed packages to reflect correct environment)

**Comment by Andy-Grigg** [comment]
Can you try this with Granta MI 2024 R2? #209 was another issue we saw related to searching for lists which was fixed in 2024 R2, and based on how the problem was fixed, I think there's a good chance it would resolve things here as well.

If this doesn't resolve the issue, we will need to set up a call to understand if there are any differences between this table and others that work. The obvious things to suggest are if the table is hidden or subject to access control.

**Comment by CalebMDMI** [comment]
Yes, it is!
